#!/bin/bash
#SBATCH --job-name=ANN     ###name of the job on CIRCE
#SBATCH --output=qe.out  ###anything that would have printed to the terminal will be found in this file
#SBATCH --error=qe.err  ###errors will be outputted to a file of this name
#SBATCH --time=4:00:00      ###Time limit for job hr:min:sec
#SBATCH --mem=8G
#SBATCH --ntasks=2
#SBATCH --nodes=1
#SBATCH --partition=circe
#################
module purge
module load apps/espresso/6.5

###count the number of files in the current directory
n=$(find  -maxdepth 1 -name 'scf.*' |wc -l)
for file in scf.*
do
    mpirun -np $SLURM_NTASKS /apps/espresso/6.5/bin/pw.x -in $file >> forces
done

